name: Publish

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download mdBook
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract mdBook
        run: |
          tar -xzf mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz

      - name: Move mdBook to PATH
        run: |
          sudo mv mdbook /usr/local/bin/

      - name: Build book
        run: |
          cd notes && mdbook build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zero2prod
          directory: notes/book
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
